export const SET_AVAILABLE_CHESTS = "SET_AVAILABLE_CHESTS";
export const UPDATE_USER_AFTER_CHEST_PURCHASE = "UPDATE_USER_AFTER_CHEST_PURCHASE";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const CHOOSE_MODE = "CHOOSE_MODE";

export const CREATE_NEW_DECK = "CREATE_NEW_DECK";
export const ADD_CARD_TO_DECK = "ADD_CARD_TO_DECK";
export const UPDATE_USER_AFTER_DECKS_UPDATE = "UPDATE_USER_AFTER_DECK_CREATION";
export const CANCEL_DECK_CREATION = "CANCEL_DECK_CREATION";
export const REMOVE_CARD_FROM_DECK = "REMOVE_CARD_FROM_DECK";
export const EDIT_DECK = "EDIT_DECK";
export const DELETE_DECK = "DELETE_DECK";

export const CHOOSE_DECK = "CHOOSE_DECK";
export const CONNECTED_TO_GAME = "CONNECTED_TO_GAME";