module.exports = {
    // From Player
    GOLD_ON_START: 1,
    MAX_HERO_HEALTH: 10,

    // From Game
    PLAYER_AMOUNT: 2,
    CARD_DRAW_COST: 1, // SAME VARIABLE ON CLIENT SIDE, CAREFUL WITH MODIFICATIONS
    MAX_CARDS_ON_BOARD: 4, // SAME VARIABLE ON CLIENT SIDE, CAREFUL WITH MODIFICATIONS
    MAX_CARDS_ON_HAND: 6, // SAME VARIABLE ON CLIENT SIDE, CAREFUL WITH MODIFICATIONS
    SUMMONED_CARD_LEVEL: 1, // SAME VARIABLE ON CLIENT SIDE, CAREFUL WITH MODIFICATIONS

    WIN_REWARD: 17,
    LOSE_REWARD: 9,
};