export const FIND_GAME = "FIND_GAME";
export const LEAVE_QUE = "LEAVE_QUE";
export const ACCEPT_GAME = "ACCEPT_GAME";
export const DISCONNECT_FROM_GAME = "DISCONNECT_FROM_GAME";
export const ABANDON_GAME = "ABANDON_GAME";
export const RECONNECT_GAME = "RECONNECT_GAME";


export const SET_AVAILABLE_CHESTS = "SET_AVAILABLE_CHESTS";
export const UPDATE_USER_AFTER_CHEST_PURCHASE = "UPDATE_USER_AFTER_CHEST_PURCHASE";
export const SET_CURRENT_USER = "SET_CURRENT_USER";


export const CHOOSE_MODE = "CHOOSE_MODE";

export const CREATE_NEW_DECK = "CREATE_NEW_DECK";
export const ADD_CARD_TO_DECK = "ADD_CARD_TO_DECK";
export const UPDATE_USER_AFTER_DECK_CREATION = "UPDATE_USER_AFTER_DECK_CREATION";
export const CANCEL_DECK_CREATION = "CANCEL_DECK_CREATION";
export const REMOVE_CARD_FROM_DECK = "REMOVE_CARD_FROM_DECK";
export const EDIT_DECK = "EDIT_DECK";
export const DELETE_DECK = "DELETE_DECK";